
class UseinsiderPageLocators:
    accept_all_btn = '[id="wt-cli-accept-all-btn"]'
    navigation_bar_block = '[class="navbar-nav overflow-y"]'
    nav_bar_items = '[class="navbar-nav overflow-y"]>li'
    more_menu_general_block = '[class="dropdown-menu show"]'
    more_menu_block_items = '[class="dropdown-menu show"]>div>div'
    team_block = '[id="career-find-our-calling"]'
    team_block_items = '[id="career-find-our-calling"]>div>div>div>div'
    see_all_teams_btn = '[class*="btn"]'
    team_href = '[id="career-find-our-calling"]>div>div>div>div>div>a'
    team_block_items_block = '[class="job-item col-12 col-lg-4 mt-5"]'
    location_block = '[id="career-our-location"]'
    life_at_insider_block = '[data-id="a8e7b90"]'
    see_all_jobs_button = '[class="button-group d-flex flex-row"]'
    location_dropdown = '[id="select2-filter-by-location-container"]'
    location_dd_results = '[id="select2-filter-by-location-results"]'
    location_dd_items = '[id="select2-filter-by-location-results"]>li'
    department_dropdown = '[id="select2-filter-by-department-container"]'
    department_dd_results = '[id="select2-filter-by-department-results"]'
    department_dd_items = '[id="select2-filter-by-department-results"]>li'
    jod_list_block = '[id="jobs-list"]'
    jod_items = '[id="jobs-list"]>div'
    job_position_name = 'p'
    job_department_name = 'span'
    job_location_name = 'div'
    job_apply_bnt = 'a'
    lever_position_name_title = '[class="posting-headline"]'
